### ISSUE TITLE
Where is CairoCanvas?

### ISSUE THREAD

**Issue by ggtrigg** [angular-rust/ux-samples#1]
I'm attempting to add a line chart to my GTK app, and am using the `ux-samples/line-chart` code as a starting point.
However, the first line:
```
use animate::CairoCanvas;
```
gives an error...
```
1 | use animate::CairoCanvas;
  |     ^^^^^^^^^^^^^^^^^^^^ no `CairoCanvas` in the root
```
which causes problems further down at:
```
let ctx = CairoCanvas::new(cr);
```

I haven't been able to find where `CairoCanvas` is defined - it doesn't seem to appear anywhere in `ux-animate` so I'm at a bit of a loss as to how to proceed.
Any suggestions would be most welcome.

**Comment by dudochkin-victor** [comment]
`animate` resides in ux-animate crate. just add this line to Cargo.toml
ux-animate = { version = "0.1", features = ["cairo"] }
Also you need to add `ux-dataflow` as the data-multiplexer. Check the dependencies in Cargo.toml file in the sample.

**Comment by dudochkin-victor** [comment]
The was some little changes in API. 
Rename the `CairoCanvas` with `Canvas`.
Just pushed updated version

**Comment by dudochkin-victor** [comment]
You may need to install additional dependencies.

sudo apt-get update && sudo apt-get install libclutter-1.0-dev libpango1.0-dev
Atm we working to remove these deps.

**Comment by ggtrigg** [comment]
Thank you for this, it has helped me get it working now.
